"""empty message

Revision ID: ba92c61bff44
Revises: f587e21251a4
Create Date: 2022-03-24 22:01:09.146520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba92c61bff44'
down_revision = 'f587e21251a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('unique_link', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'unique_link')
    # ### end Alembic commands ###
